# Generated by Django 3.0.2 on 2020-01-16 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200117_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 19, 35, 40, 991811, tzinfo=utc)),
        ),
    ]
