# Generated by Django 3.0.2 on 2020-01-16 19:40

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20200117_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('brief', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('train_csv', models.FileField(upload_to='dataset/', validators=[core.models.validate_file_extension])),
                ('test_csv', models.FileField(upload_to='dataset/', validators=[core.models.validate_file_extension])),
                ('hidden_test_csv', models.FileField(upload_to='dataset/', validators=[core.models.validate_file_extension])),
                ('train_solution_csv', models.FileField(upload_to='dataset/', validators=[core.models.validate_file_extension])),
                ('test_solution_csv', models.FileField(upload_to='dataset/', validators=[core.models.validate_file_extension])),
                ('hidden_test_solution_csv', models.FileField(upload_to='dataset/', validators=[core.models.validate_file_extension])),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 1, 16, 19, 40, 17, 506993, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2012, 1, 1, 0, 0))),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_container_path', models.CharField(max_length=300)),
                ('submission_csv', models.FileField(upload_to='dataset/', validators=[core.models.validate_file_extension])),
                ('accuracy', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
        ),
    ]
