# Generated by Django 3.0.2 on 2020-01-16 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_competition_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 19, 42, 36, 242475, tzinfo=utc)),
        ),
    ]
