# Generated by Django 3.0.2 on 2020-01-17 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200117_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 1, 18, 17, 259180, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
