# Generated by Django 3.0.2 on 2020-01-17 01:18

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20200117_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 1, 18, 50, 181945, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_path', models.CharField(blank=True, max_length=300, null=True)),
                ('container_id', models.CharField(blank=True, max_length=500, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('submission_csv', models.FileField(upload_to='dataset/', validators=[core.models.validate_file_extension])),
                ('accuracy', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
