# Generated by Django 3.0.2 on 2020-01-17 08:40

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20200117_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 8, 40, 53, 432925, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('competitor', 'competition')},
        ),
    ]
